AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 2.5
  DisplayCopNames: true
Metrics/BlockLength:
  Max: 50
Metrics/MethodLength:
  Max: 15
Style/ClassVars:
  Enabled: false
Style/OpenStructUse:
  Enabled: false