name: Release Please

on:
  push:
    branches: [ master ]

jobs:
  release-please:
    
    # Run on latest ubuntu distribution
    runs-on: ubuntu-latest
    
    # Enviroment Variables
    env:
      GEM_NAME: "warframe"
      RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      
    steps:
      # start release-please
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: ruby
          package-name: ${{ env.GEM_NAME }}
          bump-minor-pre-major: true
          version-file: "lib/${{ env.GEM_NAME }}/version.rb"
          
      # Check out this repo.  
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
        
      # Set up ruby.
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
        if: ${{ steps.release.outputs.release_created }}

      # Build and push to rubygems.org  
      - name: Release Gem
        run: |
          gem install bundler
          bundle config unset deployment
          bundle install
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        if: ${{ steps.release.outputs.release_created }}
