name: Release Ruby Gem

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: ruby
          package-name: warframe
          bump-minor-pre-major: true
          version-file: "lib/warframe/version.rb"
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
        if: ${{ steps.release.outputs.release_created }}

      - run: bundle install
        if: ${{ steps.release.outputs.release_created }}

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
      - uses: cadwallion/publish-rubygems-action@master
        env:
          token: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          RELEASE_COMMAND: rake release
        if: ${{ steps.release.outputs.release_created }}