name: Rubocop

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'lib/**'
      - 'spec/**'
      - 'Rakefile'
      - 'Thorfile'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
      - uses: reviewdog/action-rubocop@v2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review
